"""Initializing

Revision ID: bb438085ce6c
Revises: 
Create Date: 2025-12-05 22:25:11.732897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb438085ce6c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('lead_source', sa.Enum('website', 'referral', 'social_media', 'cold_call', 'event', 'other', name='leadsource'), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('lead_status', sa.Enum('new', 'contacted', 'qualified', 'proposal', 'negotiation', 'closed_won', 'closed_lost', 'nurturing', name='leadstatus'), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=True),
    sa.Column('budget', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('lead_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.Enum('sales_agent', 'head_of_sales', 'admin', name='usertype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('head_of_sales',
    sa.Column('head_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('head_id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('lead_actions',
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('call', 'email', 'meeting', 'proposal', 'follow_up', 'demo', 'other', name='leadactiontype'), nullable=False),
    sa.Column('action_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='actionpriority'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'cancelled', name='actionstatus'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_table('lead_status_history',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('sales_agents',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('agent_id'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('head_lead_oversight',
    sa.Column('oversight_id', sa.Integer(), nullable=False),
    sa.Column('head_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('oversight_type', sa.Enum('monitoring', 'intervention', 'assistance', 'review', name='oversighttype'), nullable=False),
    sa.Column('oversight_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['head_id'], ['head_of_sales.head_id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ),
    sa.PrimaryKeyConstraint('oversight_id'),
    sa.UniqueConstraint('head_id', 'lead_id', 'oversight_type')
    )
    op.create_table('lead_assignments',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('assignment_date', sa.DateTime(), nullable=True),
    sa.Column('assignment_type', sa.Enum('primary', 'secondary', 'collaborative', name='assignmenttype'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['sales_agents.agent_id'], ),
    sa.ForeignKeyConstraint(['assigned_by'], ['head_of_sales.head_id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ),
    sa.PrimaryKeyConstraint('assignment_id'),
    sa.UniqueConstraint('lead_id', 'agent_id')
    )
    op.create_table('lead_communications',
    sa.Column('communication_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('communication_type', sa.Enum('incoming', 'outgoing', name='communicationtype'), nullable=False),
    sa.Column('method', sa.Enum('phone', 'email', 'sms', 'in_person', 'video', name='communicationmethod'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('communication_date', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['sales_agents.agent_id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ),
    sa.PrimaryKeyConstraint('communication_id')
    )
    op.create_table('lead_followups',
    sa.Column('followup_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('followup_date', sa.DateTime(), nullable=False),
    sa.Column('followup_type', sa.Enum('call', 'email', 'meeting', 'message', 'other', name='followuptype'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_followup_date', sa.Date(), nullable=True),
    sa.Column('outcome', sa.Enum('positive', 'neutral', 'negative', 'no_response', name='followupoutcome'), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['sales_agents.agent_id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ),
    sa.PrimaryKeyConstraint('followup_id')
    )
    op.create_table('sales_team_assignments',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('head_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['sales_agents.agent_id'], ),
    sa.ForeignKeyConstraint(['head_id'], ['head_of_sales.head_id'], ),
    sa.PrimaryKeyConstraint('assignment_id'),
    sa.UniqueConstraint('head_id', 'agent_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_team_assignments')
    op.drop_table('lead_followups')
    op.drop_table('lead_communications')
    op.drop_table('lead_assignments')
    op.drop_table('head_lead_oversight')
    op.drop_table('sales_agents')
    op.drop_table('lead_status_history')
    op.drop_table('lead_actions')
    op.drop_table('head_of_sales')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('leads')
    # ### end Alembic commands ###
